name: domain
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.2.0
  build_resolvers: 2.1.0
  dart_style: 2.2.4
#  sqflite: 2.0.2+1

dependencies:
  flutter:
    sdk: flutter
  injectable:
  get_it:
  rxdart: 0.27.7
  dartx: 1.0.0
  freezed_annotation: 2.2.0
  shared:
    path: ../shared
  json_annotation: 4.8.0

dev_dependencies:
  build_runner: 2.2.0
  dart_code_metrics: 5.1.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.3
  json_serializable: 6.6.1
  mocktail: 0.3.0
  objectbox_generator: 1.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
